version: '3.5'

# docker-compose example file
#
# Passwords / API key can be, for example, generated locally with :
#   < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;

services:  
  influxdb:
    image: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=vertigo
      - DOCKER_INFLUXDB_INIT_PASSWORD=vertigo-password
      - DOCKER_INFLUXDB_INIT_ORG=vertigo
      - DOCKER_INFLUXDB_INIT_BUCKET=myApp
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Vl9r3iVWH4A2mS6E40niU1kt7pCjF_FGKcYimDMrFRzyHhyVUFh0CtBkbAwb3-OQyjCKlgvA8nLnZXXCkavorg==
    ports: 
      - "8086:8086"
    restart: unless-stopped
  analytics:
    image: vertigo-analytics-server
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=Vl9r3iVWH4A2mS6E40niU1kt7pCjF_FGKcYimDMrFRzyHhyVUFh0CtBkbAwb3-OQyjCKlgvA8nLnZXXCkavorg==
    depends_on:
      - influxdb
    ports:
      - "4562:4562"
    restart: unless-stopped
    