{
 "title": "Vertigo-v3",
 "tags": [
  "Vertigo",
  "RdvPref"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "app", "query": "buckets()" },
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\" \r\n\r\nschema.tagValues( \r\n bucket: \"${app}\",\r\n predicate: (r) => r._measurement == \"page\",\r\n tag: \"location\"  \r\n) "
   },
   {
    "name": "pageModule",
    "label": "prefix",
    "query": "import \"influxdata/influxdb/schema\" \r\n\r\nschema.tagValues( \r\n bucket: \"${app}\",\r\n predicate: (r) => r._measurement == \"page\",\r\n tag: \"name\",\r\n start: v.timeRangeStart, \r\n stop: v.timeRangeStop\r\n) "
   },
   {
    "name": "pageName",
    "label": "Page",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues( \r\n bucket: \"${app}\",\r\n predicate: (r) => r._measurement == \"page\",\r\n tag: \"name\",\r\n start: v.timeRangeStart, \r\n stop: v.timeRangeStop\r\n)\r\n|> filter(fn: (r) => (\"${pageModule}\"==\"all\" or r._value =~ /^\\/${pageModule}.*/ ) ) "
   }
  ]
 },
 "panels": [
  {
   "title": "hits per minutes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\r\n\r\nminus3m = date.sub(d: 3m, from:v.timeRangeStop)\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start:minus3m , stop: v.timeRangeStop) \r\n|> filter(fn: (r) => r._measurement == \"page\" and r._field ==\"duration\" ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n\r\ndata \r\n|> window(every: 1m, createEmpty:true ) \r\n|> count()\r\n|> group()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "hits per minutes",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  and r._field ==\"duration\" )\r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n\r\ndata \r\n|> window(every: 1m, createEmpty:true ) \r\n|> count()\r\n|> window(every: $__interval, timeColumn:\"_stop\")\r\n|> max()\r\n|> toFloat()\r\n|> group()\r\n|> map(fn: (r) => ({ r with hitPerSecond:r._value/60.0 }))\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "hits per seconds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\r\n\r\nminus1m = date.sub(d: 1m, from:v.timeRangeStop)\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: minus1m , stop: v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  and r._field ==\"duration\" )\r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n\r\ndata \r\n|> window(every: 1s, createEmpty:true ) \r\n|> count()\r\n|> group()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages' hits clustered by response time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) => r._measurement == \"page\" )\r\n|> filter(fn: (r) =>  r._field ==\"duration\" ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n|> window(every: $__interval, createEmpty:true ) \r\n\r\n\r\ndata0 = data \r\n|> filter(fn: (r) => (r._value < 10)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"1.duration:count<10\" }))\r\n\r\ndata1 = data \r\n|> filter(fn: (r) => (r._value > 10 and r._value <= 20)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"2.duration:count_20\"})) \r\n\r\ndata2 = data \r\n|> filter(fn: (r) => (r._value > 20 and r._value <= 50)) \r\n|> count()  \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"3.duration:count_50\"}) ) \r\n\r\ndata3 = data \r\n|> filter(fn: (r) => (r._value > 50 and r._value <= 100)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"4.duration:count_100\"}) ) \r\n\r\ndata4 = data \r\n|> filter(fn: (r) => (r._value > 100 and r._value <= 200)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"5.duration:count_200\"}) ) \r\n\r\ndata5 = data \r\n|> filter(fn: (r) => (r._value > 200 and r._value <= 500)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"6.duration:count_500\"})) \r\n\r\ndata6 = data \r\n|> filter(fn: (r) => (r._value > 500 and r._value <= 1000)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"7.duration:count_1000\"}) ) \r\n\r\ndata7 = data \r\n|> filter(fn: (r) => (r._value > 1000 and r._value <= 2000)) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start, _value:r._value, _field:\"8.duration:count_2000\"}) ) \r\n\r\ndata8 = data \r\n|> filter(fn: (r) => (r._value > 2000) ) \r\n|> count() \r\n|> map(fn: (r) => ({ _time:r._start,  _value:r._value, _field:\"9.duration:count>2000\"})) \r\n\r\nunion(tables :[data0, data1, data2, data3, data4, data5, data6, data7, data8]) \r\n|> yield() ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages' usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "countData = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  and r._field ==\"duration\" )\r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\", \"errorCode\"]) \r\n|> window(every: $__interval, createEmpty:true ) \r\n\r\ncountError = countData\r\n|> filter(fn: (r) => exists r.errorCode)\r\n|> drop(columns: [\"errorCode\"])\r\n|> count()\r\n|> group()\r\n|> set(key: \"_field\", value: \"countError\")\r\n\r\ncountTotal = countData\r\n|> drop(columns: [\"errorCode\"])\r\n|> count()\r\n|> group()\r\n|> set(key: \"_field\", value: \"count\")\r\n\r\nunion(tables :[countError, countTotal]) \r\n|> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with errorRatio:if(exists r.countError) then float(v: r.countError)*100.0/float(v:r.count) else 0.0}) ) \r\n|> yield() \r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  and r._field ==\"duration\" )\r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n|> window(every: $__interval, createEmpty:true ) \r\nquantile__q_0_7Data = data \r\n|> quantile(q: 0.7) \r\n|> duplicate(column: \"_stop\", as: \"_time\") \r\n|> group() \r\n|> set(key: \"alias\", value:\"quantile__q_0_7\" ) \r\n\r\nmedianData = data \r\n|> median() \r\n|> toFloat()\r\n|> duplicate(column: \"_stop\", as: \"_time\") \r\n|> group() \r\n|> set(key: \"alias\", value:\"median\" ) \r\n\r\nquantile__q_0_9Data = data \r\n|> quantile(q: 0.9) \r\n|> duplicate(column: \"_stop\", as: \"_time\") \r\n|> group() \r\n|> set(key: \"alias\", value:\"quantile__q_0_9\" ) \r\n\r\nunion(tables:[quantile__q_0_7Data, medianData, quantile__q_0_9Data]) \r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\", \"alias\"], valueColumn: \"_value\") \r\n|> drop(columns: [\"_start\", \"_stop\"]) \r\n|> map(fn: (r) => ({ r with duration_median: if exists r.duration_median then r.duration_median else 0.0, duration_quantile__q_0_7: if exists r.duration_quantile__q_0_7 then r.duration_quantile__q_0_7 else 0.0, duration_quantile__q_0_9: if exists r.duration_quantile__q_0_9 then r.duration_quantile__q_0_9 else 0.0}))\r\n|> rename(columns: {duration_median: \"duration:median\", duration_quantile__q_0_7: \"duration:quantile__q_0.7\", duration_quantile__q_0_9: \"duration:quantile__q_0.9\"}) \r\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "import \"strings\"\r\n\r\ndataError = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) => \r\nr._measurement == \"webservices\"\r\nand (r._field ==\"duration\" ) \r\n and (\"${location}\"==\"all\" or r.location == \"${location}\")\r\n and (r.name == \"/Post//csp-report/\")\r\n)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"]) \r\n|> window(every: $__interval, createEmpty:true ) \r\n\r\ncountData = dataError \r\n|> count() \r\n|> group()\r\n|> rename(columns: {_value: \"cspError\"}) \r\n|> yield()"
    }
   ]
  },
  {
   "title": "Most visited Pages",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  and r._field ==\"duration\" )\r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\", \"_value\", \"name\"]) \r\n\r\ndata \r\n|> count() \r\n|> group(columns:[\"_time\"]) \r\n|> sort(desc: true)\r\n|> rename(columns: { \"_value\": \"count\"}) \r\n|> top(n:50, columns:[\"count\"]) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages' mean repartition",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn : (r) => (r._field ==\"sql_duration\" ) or (r._field ==\"redis_duration\" ) or (r._field ==\"search_duration\" ) or (r._field ==\"inner_duration\" ) or (r._field ==\"piste_duration\" ) or (r._field ==\"publipostage_duration\" )) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"])\r\n|> window(every: $__interval, createEmpty:true )\r\n\r\nsumData = data \r\n|> sum() \r\n\r\ncountData = data\r\n|> filter(fn: (r) => r._field ==\"inner_duration\" )\r\n|> count()\r\n|> set(key: \"_field\", value: \"count\")\r\n\r\nunion(tables:[sumData, countData])\r\n|> group() \r\n|> toFloat()\r\n|> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ _time:r._start, \r\nsql_duration: if exists r.sql_duration then r.sql_duration/r.count else 0.0, \r\nsearch_duration: if exists r.search_duration then r.search_duration/r.count else 0.0, \r\nredis_duration: if exists r.redis_duration then r.redis_duration/r.count else 0.0, \r\npiste_duration: if exists r.piste_duration then r.piste_duration/r.count else 0.0, \r\npublipostage_duration: if exists r.publipostage_duration then r.publipostage_duration/r.count else 0.0, \r\ninner_duration: if exists r.inner_duration then r.inner_duration/r.count else 0.0}))\r\n|> yield()\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages' hit x duration repartition",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn : (r) => (r._field ==\"sql_duration\" ) or (r._field ==\"redis_duration\" ) or (r._field ==\"search_duration\" ) or (r._field ==\"inner_duration\" ) or (r._field ==\"piste_duration\" ) or (r._field ==\"publipostage_duration\" )) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) =>  \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\"])\r\n|> window(every: $__interval, createEmpty:true )\r\n\r\ndata \r\n|> sum()\r\n|> toFloat()\r\n|> group() \r\n|> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ _time:r._start, \r\nsql_duration: if exists r.sql_duration then r.sql_duration else 0.0, \r\nsearch_duration: if exists r.search_duration then r.search_duration else 0.0, \r\nredis_duration: if exists r.redis_duration then r.redis_duration else 0.0, \r\npiste_duration: if exists r.piste_duration then r.piste_duration else 0.0, \r\npublipostage_duration: if exists r.publipostage_duration then r.publipostage_duration else 0.0, \r\ninner_duration: if exists r.inner_duration then r.inner_duration else 0.0}))\r\n|> yield()\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "404 Pages",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\n data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn: (r) => r._field ==\"duration\" ) \r\n|> filter(fn: (r) => r.errorCode == \"404\") \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> keep(columns: [\"_time\", \"_value\", \"errorRequestUri\"  ]) \r\n\r\ndata \r\n|> count() \r\n|> group(columns:[\"_time\"])\r\n|> map(fn: (r) => ({ r with _time: r._time, errorRequestUri: r.errorRequestUri, _field: r._field}))\r\n|> rename(columns: {_value: \"count\"}) \r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages' Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\r\n data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn : (r) => r._field ==\"duration\" ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) => \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> filter(fn: (r) => not exists r.exception )\r\n|> keep(columns: [\"_time\", \"_value\", \"errorCode\", \"errorMsg\", \"errorDetailSecure\",\"errorRequestUri\"  ]) \r\n\r\ndata \r\n|> count() \r\n|> group(columns:[\"_time\"])\r\n|> map(fn: (r) => ({ r with errorCode: if (exists r.errorCode and exists r.errorMsg) then int(v:r.errorCode) else if (exists r.errorCode and not exists r.errorMsg) then 422 else 200, errorMsg: if (exists r.errorMsg) then r.errorMsg else if exists r.errorCode then \"Erreur utilisateur\" else \"OK\" }))\r\n//|> pivot(rowKey: [\"errorDetailSecure\"], columnKey: [\"errorMsg\"], valueColumn: \"errorCode\")\r\n|> rename(columns: {_value: \"error:count\"}) \r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most Consumming Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn : (r) => r._field ==\"duration\" ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\", \"_value\", \"name\"]) \r\n\r\ncount_duration = data\r\n  |> count()\r\n  |> set(key: \"_field\", value: \"count_duration\") \r\n  |> group()\r\n\r\nsum_duration = data\r\n  |> sum()\r\n  |> set(key: \"_field\", value: \"sum_duration\") \r\n  |> group()\r\n\r\nmin_duration = data\r\n  |> min()\r\n  |> set(key: \"_field\", value: \"min_duration\") \r\n  |> group()\r\n\r\nmax_duration = data\r\n  |> max()\r\n  |> set(key: \"_field\", value: \"max_duration\") \r\n  |> group()\r\n\r\nunion(tables: [count_duration, sum_duration, min_duration,  max_duration]) \r\n|> pivot(rowKey:[\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with mean_duration:r.sum_duration / r.count_duration  }) ) \r\n|> top(n: 20, columns:[\"mean_duration\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Durations per pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn: (r) => (r._field ==\"duration\" ) or (r._field ==\"sql_duration\" ) or (r._field ==\"redis_duration\" ) or (r._field ==\"search_duration\" )or (r._field ==\"publipostage_duration\" ) or (r._field ==\"piste_duration\" ) or (r._field ==\"inner_duration\" ) ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) => \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\", \"_field\", \"name\", \"_value\"]) \r\n\r\nmeanData = data \r\n|> mean() \r\n\r\ncallCount = data\r\n|> filter(fn: (r) => r._field ==\"duration\" )\r\n|> count()\r\n|> toFloat()\r\n|> set(key: \"_field\", value: \"count\")\r\n\r\nunion(tables:[meanData, callCount]) \r\n|> group() \r\n|> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> yield()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most consumming Tasks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"tasks\"  )\r\n|> filter(fn : (r) => r._field ==\"duration\" ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> keep(columns: [\"_time\", \"_value\", \"name\"]) \r\n\r\ncount_duration = data\r\n  |> count()\r\n  |> set(key: \"_field\", value: \"count_duration\") \r\n  |> group()\r\n\r\nsum_duration = data\r\n  |> sum()\r\n  |> set(key: \"_field\", value: \"sum_duration\") \r\n  |> group()\r\n\r\nmin_duration = data\r\n  |> min()\r\n  |> set(key: \"_field\", value: \"min_duration\") \r\n  |> group()\r\n\r\nmax_duration = data\r\n  |> max()\r\n  |> set(key: \"_field\", value: \"max_duration\") \r\n  |> group()\r\n\r\nunion(tables: [count_duration, sum_duration, min_duration,  max_duration]) \r\n|> pivot(rowKey:[\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> top(n: 20, columns:[\"sum_duration\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql usage per pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\n\r\ndata = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) =>  r._measurement == \"page\"  )\r\n|> filter(fn : (r) => (r._field ==\"duration\") or (r._field ==\"sql_duration\" ) or (r._field ==\"sql_count\" ) ) \r\n|> filter(fn: (r) => \"${location}\"==\"all\" or r.location == \"${location}\")\r\n|> filter(fn: (r) => \"${pageName}\"==\"all\" or r.name == \"${pageName}\")\r\n|> filter(fn: (r) => \"${pageModule}\"==\"all\" or r.name =~ /\\/${pageModule}.*/)\r\n|> keep(columns: [\"_time\",\"_field\", \"_value\", \"name\"]) \r\n\r\nmaxData = data \r\n|> filter(fn: (r) => r._field==\"sql_count\") \r\n|> max() \r\n|> toFloat()\r\n|> set(key: \"alias\", value:\"max\" ) \r\n\r\ncountSumData = data \r\n|> filter(fn: (r) => r._field==\"sql_count\") \r\n|> sum() \r\n|> toFloat()\r\n|> set(key: \"alias\", value:\"sum\" ) \r\n\r\ncountData = data \r\n|> filter(fn: (r) => r._field==\"duration\") \r\n|> count() \r\n|> toFloat()\r\n|> set(key: \"alias\", value:\"count\" ) \r\n\r\n\r\nsumData = data \r\n|> filter(fn: (r) => r._field==\"sql_duration\") \r\n|> sum() \r\n|> toFloat()\r\n|> set(key: \"alias\", value:\"sum\" ) \r\n\r\nunion(tables:[maxData, countSumData, countData, sumData]) \r\n|> map(fn: (r) => ({ r with name: if exists r.name then r.name else \"\"}))\r\n|> pivot(rowKey:[\"name\"], columnKey: [\"_field\", \"alias\"], valueColumn: \"_value\") \r\n|> filter(fn: (r) => r.sql_count_max>0) \r\n|> map(fn: (r) => ({ r with sql_count_mean: if exists r.sql_count_sum then r.sql_count_sum / r.duration_count else 0.0, sql_count_max: if exists r.sql_count_max then r.sql_count_max else 0.0, sql_duration_sum: if exists r.sql_duration_sum then r.sql_duration_sum else 0.0}))\r\n|> group() \r\n|> rename(columns: {sql_count_mean: \"sql_count:mean\", sql_count_max: \"sql_count:max\", sql_duration_sum: \"sql_duration:sum\"}) \r\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daemons duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket:\"${app}\") \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop) \r\n|> filter(fn: (r) => \r\nr._measurement == \"daemon\" \r\n and ((r._field ==\"duration\" ) or (r._field ==\"sql_duration\" ) or (r._field ==\"success\" )) \r\n and (\"${location}\"==\"all\" or r.location == \"${location}\")\r\n)\r\n|> keep(columns: [\"_time\", \"_field\", \"name\", \"_value\"]) \r\n|> window(every: $__interval, createEmpty:false ) \r\n\r\ndata\r\n|> max()\r\n|> pivot(rowKey: [\"name\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> pivot(rowKey: [\"_start\"], columnKey: [\"name\"], valueColumn: \"duration\")\r\n|> group()\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}