auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:

ingester:
  trace_idle_period: 10s
  #traces_per_block: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 168h #7 days

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
      #bloom_filter_false_positive: .05
      #index_downsample: 10
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

search_enabled: true